# Unitary transformation

This homework is based on the concept of unitary transformation.

Express eigenvectors of $\tilde{S}_z$ in terms of eigenvectors of $\tilde{S}_x$ using

- mathematician's way (inverse transformation way)
- physicist's way (unitary transformation way)

# Solution

Let us consider the computational basis $\{ \ket{0}, \ket{1}\}$ is the eigen basis of $\tilde{S}_z$.

Therefore, the eigen kets of $\tilde{S}_z$ are

$$
\ket{+1_z} = 
\left(
\begin{matrix}
    1 		\\
    0 	
\end{matrix}
\right)
,
\qquad
\ket{-1_z} = 
\left(
\begin{matrix}
    0 		\\
    1 	
\end{matrix}
\right)
$$

And the eigenkets of $\tilde{S}_x$ are

$$
\ket{+1_x} 
=
\frac{1}{\sqrt{2}}
\left(
\begin{matrix}
    1	\\
    1
\end{matrix}
\right)
,
\qquad
\ket{-1_x} 
=
\frac{1}{\sqrt{2}}
\left(
\begin{matrix}
    1	\\
    -1
\end{matrix}
\right)
$$

In terms of Dirac notation, 

$$
\ket{+1_x} 
=
\frac{1}{\sqrt{2}}
\left(
\ket{+1_z}  + \ket{-1_z} 
\right)
\tag{A}
$$

$$
\ket{-1_x} 
=
\frac{1}{\sqrt{2}}
\left(
\ket{+1_z}  - \ket{-1_z} 
\right)
\tag{B}
$$

# Inverse transformation way (mathematician's way)


Let us express the eigenkets of $\tilde{S}_z$ in terms of eigenkets of $\tilde{S}_x$.

((A)+ (B))/2 gives


$$
\ket{+1_z} 
=
\frac{1}{\sqrt{2}}
\left(
\ket{+1_x}  + \ket{-1_x} 
\right)
$$

Similarly ((A)-(B))/2 gives


$$
\ket{-1_z} 
=
\frac{1}{\sqrt{2}}
\left(
\ket{+1_x}  - \ket{-1_x} 
\right)
$$

# Unitary transformation way (physicist's way)

When we found the eigenvalues and eigenkets of the $\tilde{S}_x$ operator, we can consider the matrix formed due to the eigenkets of $\tilde{S}_x$ as the unitary matrix that diagonalizes $\tilde{S}_x$ under the similarity transformation matrix

$$
\tilde{S}_x \Rightarrow \tilde{U}^\dagger\tilde{S}_x \tilde{U}
$$

In [8]:
import numpy as np
from numpy import linalg as LA

In [2]:
hbar = 1

In [3]:

sx = hbar/2*np.array([[0, 1], [1, 0]])

In [4]:
sx

array([[0. , 0.5],
       [0.5, 0. ]])

In [9]:
eigenvalues, eigenvectors = LA.eig(sx)

In [10]:
eigenvalues

array([ 0.5, -0.5])

In [11]:
eigenvectors

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [12]:
unitary = eigenvectors

In [14]:
unitary

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [ ]:
np.conjugate?

In [17]:
# check diagonalization

diagonal_matrix = np.conjugate(np.transpose(unitary)) @ sx @ unitary

diagonal_matrix

array([[ 5.00000000e-01,  1.11022302e-16],
       [ 1.11022302e-16, -5.00000000e-01]])

In [18]:
# unitary transformation

ket_0_sz = np.transpose(np.array([1, 0]))
ket_1_sz = np.transpose(np.array([0, 1]))

ket_0_sz_prime = unitary @ ket_0_sz
ket_1_sz_prime = unitary @ ket_1_sz

In [19]:
ket_0_sz_prime, ket_1_sz_prime

(array([0.70710678, 0.70710678]), array([-0.70710678,  0.70710678]))

In [ ]:
np.linalg.eig?